import ChatInput from "@/components/ChatInput";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import MessageList from "@/components/MessageList";
import styles from "@/styles/Home.module.css";
import customSyles from "@/styles/Home.module.scss";
import { LanguageSelector, ModeSelector } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={customSyles.main}>
        <ModeSelector />
        <LanguageSelector  />
        <MessageList classNames={customSyles.messageList} />
        <ChatInput />
      </main>
    </>
  );
}
